name:                aquarium-solver
version:             0.1.0.0
github:              "githubuser/aquarium-solver"
license:             BSD3
author:              "Olivier Deckers"
maintainer:          "deckers.olivier@gmail.com"
copyright:           "2020 Olivier Deckers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aquarium-solver#readme>

dependencies:
- base >= 4.7 && < 5
- holmes
- hashable
- split
- combinatorial

library:
  source-dirs: src

executables:
  aquarium-solver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aquarium-solver

tests:
  aquarium-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aquarium-solver
    - hspec
    - hedgehog
    - hspec-hedgehog
